// <auto-generated />
using System;
using IssuerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IssuerApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("IssuerApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedMemberKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedOrganizationKey")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SelectedMemberKey");

                    b.HasIndex("SelectedOrganizationKey");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IssuerApp.Data.Models.Member", b =>
                {
                    b.Property<int>("MemberKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemberKey");

                    b.HasIndex("OrganizationKey");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.Achievement", b =>
                {
                    b.Property<int>("AchievementKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AchievementType")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("achievementType");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("additionalProperties");

                    b.Property<double?>("CreditsAvailable")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("creditsAvailable");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Endorsement")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("endorsement");

                    b.Property<string>("EndorsementJwt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("endorsementJwt");

                    b.Property<string>("FieldOfStudy")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("fieldOfStudy");

                    b.Property<string>("HumanCode")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("humanCode");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<string>("InLanguage")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("inLanguage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<int>("OrganizationKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specialization")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("specialization");

                    b.PrimitiveCollection<string>("Tag")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("tag");

                    b.PrimitiveCollection<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("version");

                    b.HasKey("AchievementKey");

                    b.HasIndex("OrganizationKey");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.AchievementCredential", b =>
                {
                    b.Property<int>("AchievementCredentialKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("additionalProperties");

                    b.Property<DateTimeOffset?>("AwardedDate")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("awardedDate");

                    b.Property<string>("ConfidenceMethod")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("confidenceMethod");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("@context");

                    b.Property<string>("CredentialStatus")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("credentialStatus");

                    b.Property<int?>("CredentialSubjectAchievementSubjectKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Endorsement")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("endorsement");

                    b.Property<string>("EndorsementJwt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("endorsementJwt");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("issuer");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<int?>("OrganizationKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RenderMethod")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("renderMethod");

                    b.Property<int?>("StatusListIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("validFrom");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("validUntil");

                    b.HasKey("AchievementCredentialKey");

                    b.HasIndex("CredentialSubjectAchievementSubjectKey");

                    b.HasIndex("OrganizationKey");

                    b.ToTable("AchievementCredentials");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.AchievementSubject", b =>
                {
                    b.Property<int>("AchievementSubjectKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementKey")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActivityEndDate")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("activityEndDate");

                    b.Property<DateTimeOffset?>("ActivityStartDate")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("activityStartDate");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("additionalProperties");

                    b.Property<double?>("CreditsEarned")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("creditsEarned");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("licenseNumber");

                    b.Property<int?>("MemberKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Narrative")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("narrative");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("role");

                    b.Property<int?>("SourceProfileKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Term")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("term");

                    b.PrimitiveCollection<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.HasKey("AchievementSubjectKey");

                    b.HasIndex("AchievementKey");

                    b.HasIndex("MemberKey");

                    b.HasIndex("SourceProfileKey");

                    b.ToTable("AchievementSubjects");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.Address", b =>
                {
                    b.Property<int>("AddressKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("additionalProperties");

                    b.Property<string>("AddressCountry")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("addressCountry");

                    b.Property<string>("AddressCountryCode")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("addressCountryCode");

                    b.Property<string>("AddressLocality")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("addressLocality");

                    b.Property<string>("AddressRegion")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("addressRegion");

                    b.Property<string>("Geo")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("geo");

                    b.Property<int?>("OrganizationKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostOfficeBoxNumber")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("postOfficeBoxNumber");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("postalCode");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("streetAddress");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.HasKey("AddressKey");

                    b.HasIndex("OrganizationKey");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.Criteria", b =>
                {
                    b.Property<int>("CriteriaKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("additionalProperties");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Narrative")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("narrative");

                    b.Property<int?>("OrganizationKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("CriteriaKey");

                    b.HasIndex("AchievementKey")
                        .IsUnique();

                    b.HasIndex("OrganizationKey");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.IdentifierEntry", b =>
                {
                    b.Property<int>("IdentifierEntryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("identifier");

                    b.Property<int?>("OrganizationKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.HasKey("IdentifierEntryKey");

                    b.HasIndex("OrganizationKey");

                    b.ToTable("IdentifierEntries");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.IdentityObject", b =>
                {
                    b.Property<int>("IdentityObjectKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hashed")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("hashed");

                    b.Property<string>("IdentityHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("identityHash");

                    b.Property<int?>("OrganizationKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Salt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("salt");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.HasKey("IdentityObjectKey");

                    b.HasIndex("OrganizationKey");

                    b.ToTable("IdentityObjects");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.Image", b =>
                {
                    b.Property<int>("ImageKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementCredentialKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("caption");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<int?>("OrganizationKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.HasKey("ImageKey");

                    b.HasIndex("AchievementCredentialKey")
                        .IsUnique();

                    b.HasIndex("AchievementKey")
                        .IsUnique();

                    b.HasIndex("OrganizationKey");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.Profile", b =>
                {
                    b.Property<int>("ProfileKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("additionalName");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("additionalProperties");

                    b.Property<int?>("AddressKey")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("dateOfBirth");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("email");

                    b.Property<string>("Endorsement")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("endorsement");

                    b.Property<string>("EndorsementJwt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("endorsementJwt");

                    b.Property<string>("FamilyName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("familyName");

                    b.Property<string>("FamilyNamePrefix")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("familyNamePrefix");

                    b.Property<string>("GivenName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("givenName");

                    b.Property<string>("HonorificPrefix")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("honorificPrefix");

                    b.Property<string>("HonorificSuffix")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("honorificSuffix");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<int?>("ImageKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Official")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("official");

                    b.Property<string>("PatronymicName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("patronymicName");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("phone");

                    b.PrimitiveCollection<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("url");

                    b.HasKey("ProfileKey");

                    b.HasIndex("AddressKey");

                    b.HasIndex("ImageKey");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.Organization", b =>
                {
                    b.Property<int>("OrganizationKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SigningPrivateKeyBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("SigningPublicKeyMultibase")
                        .HasColumnType("TEXT");

                    b.HasKey("OrganizationKey");

                    b.HasIndex("ProfileKey")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.Vc.TermsOfUse", b =>
                {
                    b.Property<int>("TermsOfUseKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("additionalProperties");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<int?>("OrganizationKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.HasKey("TermsOfUseKey");

                    b.HasIndex("OrganizationKey");

                    b.ToTable("TermsOfUse");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.Vc.VerifiableCredential<Library.Models.Vc.CredentialSubject, Library.Models.Vc.Issuer>", b =>
                {
                    b.Property<int>("VerifiableCredentialKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("additionalProperties");

                    b.Property<string>("ConfidenceMethod")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("confidenceMethod");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("@context");

                    b.Property<string>("CredentialSubject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("credentialSubject");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("issuer");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<int?>("OrganizationKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RenderMethod")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("renderMethod");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("validFrom");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("validUntil");

                    b.HasKey("VerifiableCredentialKey");

                    b.HasIndex("OrganizationKey");

                    b.ToTable("VerifiableCredentials");
                });

            modelBuilder.Entity("Library.Models.Vc.CredentialSchema", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<int?>("AchievementCredentialKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.Property<int?>("VerifiableCredentialKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AchievementCredentialKey");

                    b.HasIndex("VerifiableCredentialKey");

                    b.ToTable("CredentialSchema");

                    b.HasAnnotation("Relational:JsonPropertyName", "credentialSchema");
                });

            modelBuilder.Entity("Library.Models.Vc.CredentialStatus", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.Property<int?>("VerifiableCredentialKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VerifiableCredentialKey");

                    b.ToTable("CredentialStatus");

                    b.HasAnnotation("Relational:JsonPropertyName", "credentialStatus");
                });

            modelBuilder.Entity("Library.Models.Vc.DataIntegrityProof", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<int?>("AchievementCredentialKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Challenge")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("challenge");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("created");

                    b.Property<string>("Cryptosuite")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("cryptosuite");

                    b.Property<string>("Domain")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("domain");

                    b.Property<DateTimeOffset?>("Expires")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("expires");

                    b.Property<string>("Nonce")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("nonce");

                    b.Property<string>("PreviousProof")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("previousProof");

                    b.Property<string>("ProofPurpose")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("proofPurpose");

                    b.Property<string>("ProofValue")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("proofValue");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.Property<int?>("VerifiableCredentialKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerificationMethod")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("verificationMethod");

                    b.HasKey("Id");

                    b.HasIndex("AchievementCredentialKey");

                    b.HasIndex("VerifiableCredentialKey");

                    b.ToTable("DataIntegrityProof");

                    b.HasAnnotation("Relational:JsonPropertyName", "proof");
                });

            modelBuilder.Entity("Library.Models.Vc.RefreshService", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<int?>("AchievementCredentialKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.Property<int?>("VerifiableCredentialKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AchievementCredentialKey");

                    b.HasIndex("VerifiableCredentialKey");

                    b.ToTable("RefreshService");

                    b.HasAnnotation("Relational:JsonPropertyName", "refreshService");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IssuerApp.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.Member", "SelectedMember")
                        .WithMany()
                        .HasForeignKey("SelectedMemberKey");

                    b.HasOne("IssuerApp.Data.Models.Organization", "SelectedOrganization")
                        .WithMany()
                        .HasForeignKey("SelectedOrganizationKey")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SelectedMember");

                    b.Navigation("SelectedOrganization");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.Member", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.Achievement", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.Organization", "Organization")
                        .WithMany("Achievements")
                        .HasForeignKey("OrganizationKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.AchievementCredential", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.OpenBadges.AchievementSubject", "CredentialSubject")
                        .WithMany()
                        .HasForeignKey("CredentialSubjectAchievementSubjectKey");

                    b.HasOne("IssuerApp.Data.Models.Organization", "Organization")
                        .WithMany("AchievementCredentials")
                        .HasForeignKey("OrganizationKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CredentialSubject");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.AchievementSubject", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.OpenBadges.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementKey")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("IssuerApp.Data.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberKey")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("IssuerApp.Data.Models.OpenBadges.Profile", "Source")
                        .WithMany()
                        .HasForeignKey("SourceProfileKey")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Achievement");

                    b.Navigation("Member");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.Address", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.Criteria", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.OpenBadges.Achievement", "Achievement")
                        .WithOne("Criteria")
                        .HasForeignKey("IssuerApp.Data.Models.OpenBadges.Criteria", "AchievementKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IssuerApp.Data.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Achievement");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.IdentifierEntry", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.IdentityObject", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.Image", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.OpenBadges.AchievementCredential", "AchievementCredential")
                        .WithOne("Image")
                        .HasForeignKey("IssuerApp.Data.Models.OpenBadges.Image", "AchievementCredentialKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IssuerApp.Data.Models.OpenBadges.Achievement", "Achievement")
                        .WithOne("Image")
                        .HasForeignKey("IssuerApp.Data.Models.OpenBadges.Image", "AchievementKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IssuerApp.Data.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Achievement");

                    b.Navigation("AchievementCredential");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.Profile", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.OpenBadges.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressKey");

                    b.HasOne("IssuerApp.Data.Models.OpenBadges.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageKey");

                    b.Navigation("Address");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.Organization", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.OpenBadges.Profile", "Profile")
                        .WithOne()
                        .HasForeignKey("IssuerApp.Data.Models.Organization", "ProfileKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.Vc.TermsOfUse", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.Vc.VerifiableCredential<Library.Models.Vc.CredentialSubject, Library.Models.Vc.Issuer>", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Library.Models.Vc.CredentialSchema", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.OpenBadges.AchievementCredential", null)
                        .WithMany("CredentialSchema")
                        .HasForeignKey("AchievementCredentialKey");

                    b.HasOne("IssuerApp.Data.Models.Vc.VerifiableCredential<Library.Models.Vc.CredentialSubject, Library.Models.Vc.Issuer>", null)
                        .WithMany("CredentialSchema")
                        .HasForeignKey("VerifiableCredentialKey");
                });

            modelBuilder.Entity("Library.Models.Vc.CredentialStatus", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.Vc.VerifiableCredential<Library.Models.Vc.CredentialSubject, Library.Models.Vc.Issuer>", null)
                        .WithMany("CredentialStatus")
                        .HasForeignKey("VerifiableCredentialKey");
                });

            modelBuilder.Entity("Library.Models.Vc.DataIntegrityProof", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.OpenBadges.AchievementCredential", null)
                        .WithMany("Proof")
                        .HasForeignKey("AchievementCredentialKey");

                    b.HasOne("IssuerApp.Data.Models.Vc.VerifiableCredential<Library.Models.Vc.CredentialSubject, Library.Models.Vc.Issuer>", null)
                        .WithMany("Proof")
                        .HasForeignKey("VerifiableCredentialKey");
                });

            modelBuilder.Entity("Library.Models.Vc.RefreshService", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.OpenBadges.AchievementCredential", null)
                        .WithMany("RefreshService")
                        .HasForeignKey("AchievementCredentialKey");

                    b.HasOne("IssuerApp.Data.Models.Vc.VerifiableCredential<Library.Models.Vc.CredentialSubject, Library.Models.Vc.Issuer>", null)
                        .WithMany("RefreshService")
                        .HasForeignKey("VerifiableCredentialKey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuerApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IssuerApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.Achievement", b =>
                {
                    b.Navigation("Criteria")
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.OpenBadges.AchievementCredential", b =>
                {
                    b.Navigation("CredentialSchema");

                    b.Navigation("Image");

                    b.Navigation("Proof");

                    b.Navigation("RefreshService");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.Organization", b =>
                {
                    b.Navigation("AchievementCredentials");

                    b.Navigation("Achievements");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("IssuerApp.Data.Models.Vc.VerifiableCredential<Library.Models.Vc.CredentialSubject, Library.Models.Vc.Issuer>", b =>
                {
                    b.Navigation("CredentialSchema");

                    b.Navigation("CredentialStatus");

                    b.Navigation("Proof");

                    b.Navigation("RefreshService");
                });
#pragma warning restore 612, 618
        }
    }
}
