using Microsoft.AspNetCore.Razor.TagHelpers;
using System.Text.RegularExpressions;

namespace VerifierApp.Helpers
{
    /// <summary>
    /// Post-processes labels generated by the built-in LabelTagHelper to split PascalCase
    /// property names into words (e.g. "HumanCode" → "Human Code").
    /// Explicit label text and [Display(Name = "...")] values are passed through unchanged.
    /// </summary>
    [HtmlTargetElement("label", Attributes = "asp-for")]
    public class SplitCaseLabelTagHelper : TagHelper
    {
        // Run after the built-in LabelTagHelper (Order = 0)
        public override int Order => 1;

        private static readonly Regex SplitCaseRegex = new(
            @"(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])",
            RegexOptions.Compiled);

        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
            await base.ProcessAsync(context, output);

            var content = output.Content.GetContent();
            if (!string.IsNullOrWhiteSpace(content))
            {
                output.Content.SetContent(SplitCaseRegex.Replace(content, " "));
            }
        }
    }
}
