using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace IssuerApp.Helpers
{
    /// <summary>
    /// Post-processes labels generated by the built-in LabelTagHelper (and further processed by
    /// <see cref="SplitCaseLabelTagHelper"/>) to append " *" when the bound field is required.
    /// </summary>
    [HtmlTargetElement("label", Attributes = "asp-for")]
    public class RequiredLabelTagHelper : TagHelper
    {
        // Run after SplitCaseLabelTagHelper (Order = 1)
        public override int Order => 2;

        [HtmlAttributeName("asp-for")]
        public ModelExpression? For { get; set; }

        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
            await base.ProcessAsync(context, output);

            if (For?.Metadata?.IsRequired == true)
            {
                var content = output.Content.GetContent();
                output.Content.SetContent(content + " *");
            }
        }
    }
}
