using System.Threading.Tasks;
using WalletApp.Data.Models;

namespace WalletApp.Services
{
    /// <summary>
    /// Represents the Holder Coordinator role from the VCALM spec.
    /// The student's wallet uses this service to initiate and complete an exchange
    /// that was started by an Issuer Coordinator.
    /// </summary>
    public interface IHolderExchangeService
    {
        /// <summary>
        /// Initiates a VCALM exchange using the provided Interaction URL (§3.7.1).
        ///
        /// Steps performed:
        ///   1. GET interactionUrl → Protocols
        ///   2. POST InviteResponse to Protocols.inviteRequest
        ///   3. POST empty body {} → issuer returns DIDAuthentication VPR with challenge
        ///   4. Build and sign a DIDAuth VP using the holder's key; POST it back
        ///   5. Return the server message containing the issued VerifiablePresentation.
        /// </summary>
        /// <param name="interactionUrl">The Interaction URL generated by the issuer.</param>
        /// <param name="holder">
        /// The wallet's holder record, including the DID and signing key used to prove
        /// DID ownership in the DIDAuthentication round-trip.
        /// </param>
        Task<HolderExchangeResult> ReceiveCredentialAsync(string interactionUrl, Holder? holder = null);
    }
}
